joint_inits:
  transx_joint: 0.0
  transy_joint: 0.0
  transz_joint: 0.0
  rotx_joint: 0.0
  roty_joint: 0.0
  rotz_joint: 0.0

add_odom_joints:
  lin_odom_x_joint: false
  lin_odom_y_joint: false
  lin_odom_z_joint: false
  ang_odom_x_joint: false
  ang_odom_y_joint: false
  ang_odom_z_joint: false

max_time_step: 0.005 # Maximal time step (bigger value <=> faster but more unstable)

pub_object_marker_array:
  free_bodies_only: True # Only publish the marker array of free objects
  robot_bodies_rate: 0.0 # The frequency to publish the marker array of robot
  world_bodies_rate: 0.0 # The frequency to publish the marker array of world
  spawned_object_bodies_rate: 0.0 # The frequency to publish the marker array of spawned objects

pub_tf:
  free_bodies_only: True # Only publish the tf of free objects
  robot_bodies_rate: 0.0 # The frequency to publish the tf of robot
  world_bodies_rate: 0.0 # The frequency to publish the tf of world
  spawned_object_bodies_rate: 60.0 # The frequency to publish the tf of spawned objects

pub_object_state_array:
  free_bodies_only: True # Only publish the object state of free objects
  robot_bodies_rate: 0.0 # The frequency to publish the object state of robot
  world_bodies_rate: 60.0 # The frequency to publish the object state of world
  spawned_object_bodies_rate: 60.0 # The frequency to publish the object state of spawned objects

pub_joint_states:
  robot_bodies_rate: 60.0 # The frequency to publish the joint states of robot
  world_bodies_rate: 60.0 # The frequency to publish the joint states of world
  spawned_object_bodies_rate: 0.0 # The frequency to publish the joint states of spawned objects

pub_base_pose_rate: 60.0 # The frequency to publish the base pose of the robot

pub_sensor_data_rate: 60 # The frequency to publish the sensor data

spawn_and_destroy_objects_rate: 10.0 # The frequency to spawn and destroy the objects

spawn_object_count_per_cycle: 20 # The maximal number of objects to spawn per cycle

root_frame_id: map # The frame id of the world (normally 'map' for fixed-based robots and 'odom' for mobile robots)